name: Test

on:
  push:
    branches: [ "test" ]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - run: echo "hello,world"
      - run: echo "${{ github.repository }}"
      - run: echo "${{ github.ref_name }}"